inital testing
DIMO-Network/dimo-developer-console pull request #29
Opened 2024-09-11 12:39 UTC by lauradeng23

2024-09-23 15:20 UTC, Asfiroth commented on src/services/smartContract.ts
> +const web3 = new Web3('https://polygon-mumbai.infura.io/v3/YOUR_INFURA_PROJECT_ID'); // Replace with Infura ID
set the infura project id as an env variable

2024-09-23 15:22 UTC, Asfiroth commented on src/services/smartContract.ts
> +const contractAddress = '0x523d4a08cf149f1Ada8113B3b3400234236Bb5E8';
move this, to configurations files depending on environment, check how DIMO token contract address is handled.

2024-09-23 15:23 UTC, Asfiroth commented on src/services/smartContract.ts
> +      console.log('DIMO tokens successfully converted to DIMO Credits and burned.');
please don't leave console.log's, if this is relevant to the user use a notification with the notification context.

2024-09-23 15:24 UTC, Asfiroth commented
@lauradeng23 please add the `.idea` to gitignore

2024-09-24 03:48 UTC, YokySantiago requested changes
Left some comments on the PR and in addition some questions for you, are the `.idea` files needed in the repository? are they helpful to keep the same code style? can be the `.idea/.gitignore` file merged into the one located in the root folder?

2024-09-24 03:48 UTC, YokySantiago commented on src/app/api/webhook/route.ts
> +    const { status, txHash } = await req.json(); // Parsing JSON from the request body
the comment is unnecessary since it's self explanatory
```suggestion
    const { status, txHash } = await req.json();
```

2024-09-24 03:48 UTC, YokySantiago commented on src/app/api/webhook/route.ts
> +      // Call the burn DIMO token function if the payment was successful
the comment is unnecessary since it's self explanatory
```suggestion
```

2024-09-24 03:48 UTC, YokySantiago commented on src/app/api/webhook/route.ts
> +    console.error('Error handling webhook:', error);
Since this messages are logged in Vercel, let's add the txHash to facilitate debugging

2024-09-24 03:48 UTC, YokySantiago commented on src/components/BuyCreditsModal/BuyCreditsModal.tsx
> +  const iframeUrl = `https://ramptest.alchemypay.org/?apiKey=${process.env.NEXT_PUBLIC_API_KEY}&cryptoAddress=${process.env.NEXT_PUBLIC_CRYPTO_ADDRESS}&network=${process.env.NEXT_PUBLIC_NETWORK}`;
This line is too long, let's get the env variables first
```suggestion
  const { 
    NEXT_PUBLIC_API_KEY: nextPublicApiKey,
    NEXT_PUBLIC_CRYPTO_ADDRESS: nextPublicCryptoAddress,
    NEXT_PUBLIC_NETWORK: nextPublicNetwork,
  } = process.env
  const iframeUrl = `https://ramptest.alchemypay.org/?apiKey=${nextPublicApiKey}&cryptoAddress=${nextPublicCryptoAddress}&network=${nextPublicNetwork}`;
```

2024-09-24 03:48 UTC, YokySantiago commented on src/services/smartContract.ts
> +const web3 = new Web3('https://polygon-mumbai.infura.io/v3/YOUR_INFURA_PROJECT_ID'); // Replace with Infura ID
Let's use the config files under the config folder

2024-09-24 03:48 UTC, YokySantiago commented on src/services/smartContract.ts
> +];
What about moving this json into a new json file?

2024-09-24 03:48 UTC, YokySantiago commented on src/services/smartContract.ts
> +export async function mintDimoCredits(txHash: string) {
There are some comments that can be removed since the next line is self explanatory

2024-09-24 03:48 UTC, YokySantiago commented on src/services/smartContract.ts
> +    console.error('Error minting DIMO Credits:', error);
Let's add the txHash to facilitate debugging

2024-09-30 22:46 UTC, jamesliupenn commented
The latest changes that @lauradeng23 pushed out seems to have resolved all of the comments. @Asfiroth please review this again so we can get it out to the staging branch for e2e testing (USD -> DIMO -> DCX flow) + Global Accounts.

2024-10-01 03:03 UTC, YokySantiago commented on src/config/dimoContract.json
> +[
Let's move this file under `src/contracts`

2024-10-01 03:10 UTC, YokySantiago requested changes
Last comment

2024-10-01 15:31 UTC, merged