DEVR-114 New landing page
DIMO-Network/dimo-developer-console pull request #36
Opened 2024-10-08 03:54 UTC by lauradeng23

2024-10-08 18:47 UTC, jamesliupenn commented
@lauradeng23 please make sure you aim at staging for PRs, thanks!

2024-10-10 03:43 UTC, YokySantiago requested changes

2024-10-10 03:43 UTC, YokySantiago commented on src/app/app/components/View/View.css
Let's use tailwind styles 
https://tailwindcss.com/docs/utility-first

2024-10-10 03:43 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +    if (isLoading || loadingApps) {
I noticed multiple return statements based on different scenarios. To keep the component cleaner and more maintainable, we typically use a single return and conditionally render sections based on variables. This reduces redundancy and centralizes the rendering logic. Here's an example of how it could be refactored:

```jsx
return (
  <div>
    {isLoading && <div>Loading</div>}
    {hasAccess ? <div>You have access</div> : <div>Access denied</div>}
    <div>This section is always displayed</div>
  </div>
);
```

2024-10-10 13:38 UTC, lauradeng23 commented on src/app/app/components/View/View.tsx
> +    const [dcxBalance, setDcxBalance] = useState<number>(0); // Placeholder for DCX balance
@YokySantiago I am unsure what to put here to get the dcx balance

2024-10-16 12:23 UTC, YokySantiago requested changes

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +    const [dcxBalance, setDcxBalance] = useState<number>(0); // Placeholder for DCX balance
We need to create a hook to get this balance, there's a discord conversation about this

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
We are using 2 spaces for indentation

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                    setApps(response.results); // Use results from the API
This code is self explanatory so we don't need this comments
```suggestion
                    const response = await getMyApps();
                    setApps(response.results);
```

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +            ) : (
We can use the inline rendering with logical operator to avoid a ternary expression here
https://legacy.reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

```suggestion
            {(isLoading || loadingApps) && <div>Loading...</div>}
```

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                                </div>
Let's create a component inside `src/app/app/components` for this section for readability

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                                <button className="create-new-app-btn">+ Create new</button>
There's already a Button component, let's use it

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                                            <button
Let's use the button component

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                                <button className="get-credits-btn">Get Credits</button>
Let's use the button component

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                            <div className="attention-box">
Let's create a component inside `src/app/app/components` for readability

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                                        <button className="create-app-btn">Create an App</button>
Lets use the button component

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                                </div>
This section is duplicated below, let's create a component inside `src/app/app/components`

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                            </div>
Let's create a component inside `src/app/app/components` for readablity

2024-10-16 12:23 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                    {!hasDCXBalance && !hasApps && !isOnboardingCompleted && (
This is doing something similar to the first version with the returns. Write all the components for the different scenarios on the same page and at the same level, then enable or disable specific sections or components using the inline rendering with logical operator. This way we avoid duplicating code and improve readability

2024-10-22 17:26 UTC, Asfiroth commented on src/app/app/components/View/View.tsx
> +        transport: http('https://rpc.zerodev.app/api/v2/bundler/f4d1596a-edfd-4063-8f99-2d8835e07739'),
url should be an `.env` variable

2024-10-23 02:15 UTC, Allyson-English commented on src/app/app/components/View/View.tsx
> +
if we import the contract mapping from the transactions sdk to make the mapping easier (`npm install @dimo-network/transactions`)

we can then define the contract mapping like this:

```
import {
  CHAIN_ABI_MAPPING,
  ENVIRONMENT,
  ENV_MAPPING,
  ContractType,
} from '@dimo-network/transactions';

export const contractMapping =
  CHAIN_ABI_MAPPING[ENV_MAPPING.get("dev") ?? ENVIRONMENT.PROD].contracts;
```

in the above example, you should be able to copy/ paste as is (updating where it says "dev" with an .env variable).  then you can call it below in the public client as you're doing and it should populate with the right address and abi

2024-10-23 04:05 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +    };
This method should be inside AppList component

2024-10-23 04:05 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +                    const accountAddress = '<USER_GLOBAL_ACCOUNT_ADDRESS>';
You can get this address by using the `useGlobalAccounts` hook, the property is organizationInfo.walletAddress

2024-10-23 04:05 UTC, YokySantiago commented on src/app/app/components/View/View.tsx
> +    };
Did you check this function?
https://docs.zerodev.app/smart-wallet/defi-integrations#listing-tokens

2024-11-04 13:00 UTC, Asfiroth requested changes

2024-11-04 13:00 UTC, Asfiroth commented on src/app/app/components/View/View.tsx
> +                <div>Loading...</div>
this section had a loader, why did it changed?

2024-11-05 16:36 UTC, merged