[DEVR-123] Onramp
DIMO-Network/dimo-developer-console pull request #37
Opened 2024-10-15 15:19 UTC by Asfiroth

2024-10-24 22:51 UTC, YokySantiago requested changes

2024-10-24 22:51 UTC, YokySantiago commented on src/components/BuyCreditsModal/BuyCredits/CryptoPurchase.tsx
> +        maticAmount: event.payload.session.destination_crypto_amount, //event.payload.session.destination_crypto_amount,
```suggestion
        maticAmount: event.payload.session.destination_crypto_amount, 
```

2024-10-24 22:51 UTC, YokySantiago commented on src/components/BuyCreditsModal/BuyCredits/ProcessComplete.tsx
> +      <h1>Successfully Minted DCX</h1>
```suggestion
      <Title component="h1">Successfully Minted DCX</Title>
```

2024-10-24 22:51 UTC, YokySantiago commented on src/config/preview.ts
> +  '0x52D03752872F30B6AcD26979FD5EB7213bA62DaF';
Let's remove it since it's using the default ones

2024-10-24 22:51 UTC, YokySantiago commented on src/components/BuyCreditsModal/BuyCredits/ProcessComplete.tsx
> +    <div className="success-card">
```suggestion
    <Card>
```

2024-10-24 22:51 UTC, YokySantiago commented on src/contracts/pool.json
Let's remove this one

2024-10-25 14:16 UTC, jamesliupenn commented on src/hooks/useGlobalAccount.ts
> +    } catch (e) {
When the fund fails to swap to DIMO, I think we need to show WMATIC in your hook that looks up crypto balance - @YokySantiago @Asfiroth 

That make sense? I'm guessing there's a chance something in between fails 🤔

2024-10-25 15:33 UTC, jamesliupenn requested changes

2024-10-25 15:33 UTC, jamesliupenn commented on src/components/BuyCreditsModal/BuyCredits/CreditsAmount.tsx
> +
I would also suggest adding in a MINIMUM_CREDITS of 10000 DCX, which is equivalent to $10 USD. Anything less than 10 USD isn't efficient and probably useless at this point.

2024-10-25 15:33 UTC, jamesliupenn commented on src/components/BuyCreditsModal/BuyCredits/CreditsAmount.tsx
> +      credits: 0,
Then update the default to MINIMUM_CREDITS

2024-10-25 15:33 UTC, jamesliupenn commented on src/components/BuyCreditsModal/BuyCredits/CreditsAmount.tsx
> +  const credits = watch('credits', 0);
Also wanna watch MINIMUM_CREDITS instead

2024-10-25 15:33 UTC, jamesliupenn commented on src/components/BuyCreditsModal/BuyCredits/CreditsAmount.tsx
> +      />
Add a rule here for minimum credits

2024-10-31 12:32 UTC, YokySantiago commented on src/config/index.ts
> +import { DCX_ADDRESS, MINIMUM_CREDITS } from './default';
This import is unnecesary
```suggestion
```

2024-10-31 12:33 UTC, YokySantiago requested changes
One last comment

2024-10-31 15:47 UTC, YokySantiago approved these changes

2024-10-31 15:53 UTC, jamesliupenn approved these changes

2024-10-31 15:53 UTC, jamesliupenn commented on src/config/default.ts
> +export const MINIMUM_CREDITS = 10000;
💘 config approach ;)

2024-10-31 15:53 UTC, jamesliupenn commented on src/components/BuyCreditsModal/BuyCredits/ProcessComplete.tsx
> +      <Title component="h1">Successfully Minted DCX</Title>
I'm kind of hesitant to see `Mint` in this step. Maybe just `Successfully Purchased DCX`?

2024-10-31 15:53 UTC, jamesliupenn commented on src/components/BuyCreditsModal/BuyCredits/ProcessComplete.tsx
> +      <Title component="h1">Successfully Minted DCX</Title>
But if we already have mint everywhere else, it's fine. We can change languages later

2024-10-31 16:12 UTC, merged