SM-1294
DIMO-Network/dimo-developer-console pull request #53
Opened 2024-12-04 07:03 UTC by lauradeng23

2024-12-04 07:07 UTC, lauradeng23 commented
Getting a 404 when I try to access localhost:8080/webhooks (backend endpoints in vehicle events service)

 curl -X GET http://localhost:8080/webhooks -H "Origin: http://localhost:3000"
returns all my webhooks
and
curl -i -X GET http://localhost:8080/webhooks   
returns 200 ok

please help

2025-01-08 17:52 UTC, Asfiroth requested changes
let's address this comments first @lauradeng23

2025-01-08 17:52 UTC, Asfiroth commented on src/services/webhook.ts
> +        throw error;
Not sure what's the point of catching and re throwing the error

2025-01-08 17:52 UTC, Asfiroth commented on src/services/webhook.ts
> +        const response = await axios.post(`${API_BASE_URL}/webhooks`, payload, {
please type the responses

2025-01-08 17:52 UTC, Asfiroth commented on src/app/integrations/page.tsx
> +    return <IntegrationsPage />;
let's use the same templating as the other pages, also let's add the layout

2025-01-09 04:19 UTC, YokySantiago requested changes
I left some comments on the PR

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/DeleteConfirmModal.tsx
Indent this file using 2 spaces

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/DeleteConfirmModal.tsx
> +                    <button className="delete-webhook-button" onClick={onDelete}>
Let's use the button component

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/DeleteConfirmModal.tsx
> +                    <button className="cancel-button" onClick={onCancel}>
Let's use the button component

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/DeleteConfirmModal.tsx
> +                <h2>Confirm Deletion</h2>
There's a title componet, let's use it

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/Integrations.css
Let's use tailwind classes

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/Integrations.tsx
> +                <h1 className="integrations-title">Webhooks</h1>
Let's use the title component

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/Integrations.tsx
> +                <button
Let's use the Button component

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/Integrations.tsx
> +                    }}
Let's create a function to handle the webhook creation
```suggestion
                    onClick={handleCreate}
```

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/Integrations.tsx
Change the indentation to 2 spaces

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/WebhookForm.tsx
Change the indentation to 2 spaces

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/WebhookForm.tsx
> +    return (
Use the components we have for textfields, select, and title

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/WebhookTable.tsx
> +            <table className="webhook-table">
There's a table component, let's use it

2025-01-09 04:19 UTC, YokySantiago commented on src/components/Integrations/WebhookTable.tsx
change the indentation to 2 spaces

2025-01-09 04:19 UTC, YokySantiago commented on src/hooks/useWebhooks.ts
Change the indentation to 2 spaces

2025-01-09 04:19 UTC, YokySantiago commented on src/services/webhook.ts
Change the identatio to 2 spaces

2025-01-09 04:19 UTC, YokySantiago commented on src/services/webhook.ts
> +const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
Let's get this one from the config file

2025-01-09 04:19 UTC, YokySantiago commented on src/services/webhook.ts
> +    const response = await axios.get<string[]>(`${API_BASE_URL}/webhooks/signals`, {
Is there a filter by user?

2025-01-09 04:19 UTC, YokySantiago commented on src/services/webhook.ts
> +    const response = await axios.get<Webhook[]>(`${API_BASE_URL}/webhooks`, {
Is there a filter by user?

2025-01-09 04:19 UTC, YokySantiago commented on src/services/webhook.ts
> +    const payload = {
We should not default the values here, should we?

2025-01-09 04:19 UTC, YokySantiago commented on src/types/webhook.ts
Change the indentation to 2 spaces

2025-01-09 04:19 UTC, YokySantiago commented on package.json
> +    "axios": "^1.7.8",
We are using xior instead of axios

2025-01-10 16:29 UTC, merged